# Demo cluster and Docker registry installation play
---
  - name: Frontend node setup
    hosts: frontend
    become: true
    roles:
      - nginx
  
  - name: Backend nodes setup
    hosts: backend
    become: true
    roles:
      - backend

